import type {
  AiAnalysis,
  AiFeedback,
  Incident,
  IncidentLog,
  ResolutionHistory,
  Runbook,
} from '../types/incident'

export const incidents: Incident[] = [
  {
    id: 101,
    title: 'Payment API 502 Bad Gateway',
    serviceName: 'payment-api',
    severity: 'HIGH',
    status: 'ANALYZING',
    source: 'ALERT',
    owner: 'payment-oncall',
    affectedUsers: 1840,
    description:
      'Checkout requests intermittently fail with 502 responses when payment authorization calls pass through the edge gateway.',
    occurredAt: '2026-07-07T14:20:00',
    updatedAt: '2026-07-07T14:36:00',
    keywords: ['502', 'upstream timeout', 'SocketTimeoutException', 'payment'],
    logIds: [1001, 1002],
    relatedRunbookIds: [201, 202],
    similarIncidentIds: [98, 94],
    analysisId: 301,
  },
  {
    id: 98,
    title: 'External SaaS connection reset',
    serviceName: 'sync-worker',
    severity: 'MEDIUM',
    status: 'MITIGATED',
    source: 'ALERT',
    owner: 'platform-oncall',
    affectedUsers: 420,
    description:
      'Background sync failed for customer profile updates because the external SaaS endpoint reset long-running connections.',
    occurredAt: '2026-07-05T09:12:00',
    updatedAt: '2026-07-05T10:02:00',
    keywords: ['Connection reset by peer', 'retry', 'external api'],
    logIds: [1003],
    relatedRunbookIds: [202],
    similarIncidentIds: [101, 94],
    analysisId: 302,
    resolutionId: 401,
    feedbackId: 501,
  },
  {
    id: 94,
    title: 'Batch job delayed by API latency',
    serviceName: 'batch-worker',
    severity: 'LOW',
    status: 'RESOLVED',
    source: 'MANUAL',
    owner: 'data-platform',
    affectedUsers: 0,
    description:
      'Nightly settlement batch finished late after external settlement API latency increased above the retry backoff window.',
    occurredAt: '2026-07-02T22:00:00',
    updatedAt: '2026-07-03T00:15:00',
    keywords: ['batch delayed', 'external api latency', 'settlement'],
    logIds: [1004],
    relatedRunbookIds: [203],
    similarIncidentIds: [101, 98],
    analysisId: 303,
    resolutionId: 402,
  },
  {
    id: 87,
    title: 'DB connection pool exhausted',
    serviceName: 'order-api',
    severity: 'CRITICAL',
    status: 'OPEN',
    source: 'ALERT',
    owner: 'order-oncall',
    affectedUsers: 5200,
    description:
      'Order placement latency increased sharply after the order API exhausted HikariCP connections during a traffic spike.',
    occurredAt: '2026-06-28T16:45:00',
    updatedAt: '2026-06-28T16:51:00',
    keywords: ['HikariPool', 'connection timeout', 'order'],
    logIds: [1005, 1006],
    relatedRunbookIds: [204],
    similarIncidentIds: [101, 94],
  },
  {
    id: 82,
    title: 'Deployment introduced auth token validation errors',
    serviceName: 'auth-api',
    severity: 'HIGH',
    status: 'CLOSED',
    source: 'DEPLOYMENT',
    owner: 'identity-team',
    affectedUsers: 960,
    description:
      'New auth API deployment rejected valid tokens due to a rotated signing key cache mismatch.',
    occurredAt: '2026-06-22T11:08:00',
    updatedAt: '2026-06-22T12:44:00',
    keywords: ['JWT', 'signing key', '401'],
    logIds: [1007],
    relatedRunbookIds: [205],
    similarIncidentIds: [87],
    analysisId: 304,
    resolutionId: 403,
    feedbackId: 502,
  },
]

export const incidentLogs: IncidentLog[] = [
  {
    id: 1001,
    incidentId: 101,
    level: 'ERROR',
    source: 'edge-gateway',
    capturedAt: '2026-07-07T14:22:10',
    extractedKeywords: ['502', 'upstream timeout'],
    message:
      'upstream timed out while reading response header from upstream, client=10.1.22.41, request=POST /payments/authorize, upstream=payment-api',
  },
  {
    id: 1002,
    incidentId: 101,
    level: 'ERROR',
    source: 'payment-api',
    capturedAt: '2026-07-07T14:23:02',
    extractedKeywords: ['SocketTimeoutException', 'payment'],
    message:
      'java.net.SocketTimeoutException: Read timed out at PaymentGatewayClient.authorize(PaymentGatewayClient.java:84)',
  },
  {
    id: 1003,
    incidentId: 98,
    level: 'WARN',
    source: 'sync-worker',
    capturedAt: '2026-07-05T09:16:18',
    extractedKeywords: ['Connection reset by peer', 'retry'],
    message:
      'ProfileSyncJob retry exhausted: java.net.SocketException: Connection reset by peer, provider=crm-saas',
  },
  {
    id: 1004,
    incidentId: 94,
    level: 'WARN',
    source: 'batch-worker',
    capturedAt: '2026-07-02T22:18:46',
    extractedKeywords: ['batch delayed', 'external api latency'],
    message:
      'settlement-batch delayed: p95 external API latency 8.2s, retry window exceeded',
  },
  {
    id: 1005,
    incidentId: 87,
    level: 'ERROR',
    source: 'order-api',
    capturedAt: '2026-06-28T16:46:23',
    extractedKeywords: ['HikariPool', 'connection timeout'],
    message:
      'HikariPool-1 - Connection is not available, request timed out after 30000ms',
  },
  {
    id: 1006,
    incidentId: 87,
    level: 'WARN',
    source: 'order-api',
    capturedAt: '2026-06-28T16:49:11',
    extractedKeywords: ['order', 'latency'],
    message: 'OrderCreateService p95 latency exceeded 12s during flash sale traffic.',
  },
  {
    id: 1007,
    incidentId: 82,
    level: 'ERROR',
    source: 'auth-api',
    capturedAt: '2026-06-22T11:10:03',
    extractedKeywords: ['JWT', 'signing key', '401'],
    message:
      'TokenValidationException: kid not found in signing key cache, response=401',
  },
]

export const runbooks: Runbook[] = [
  {
    id: 201,
    title: 'Nginx 502 Bad Gateway response procedure',
    serviceName: 'edge-gateway',
    category: 'Gateway',
    owner: 'platform-oncall',
    updatedAt: '2026-07-01T10:00:00',
    triggerKeywords: ['502', 'upstream timeout', 'Bad Gateway'],
    steps: [
      'Check gateway upstream timeout and error-rate charts.',
      'Confirm target service pod health and recent deployment history.',
      'Compare timeout spikes with downstream API latency.',
      'Temporarily raise gateway timeout only after downstream ownership confirms safety.',
    ],
    linkedIncidentIds: [101],
  },
  {
    id: 202,
    title: 'External provider timeout and retry checklist',
    serviceName: 'payment-api',
    category: 'External API',
    owner: 'payment-oncall',
    updatedAt: '2026-06-29T15:20:00',
    triggerKeywords: ['SocketTimeoutException', 'Connection reset by peer', 'retry'],
    steps: [
      'Verify provider status page and synthetic check results.',
      'Inspect retry queue depth and retry exhaustion count.',
      'Switch to degraded mode when retry backlog exceeds the service threshold.',
      'Prepare customer impact note for partial payment authorization delays.',
    ],
    linkedIncidentIds: [101, 98],
  },
  {
    id: 203,
    title: 'Settlement batch delay recovery',
    serviceName: 'batch-worker',
    category: 'Batch',
    owner: 'data-platform',
    updatedAt: '2026-06-18T09:40:00',
    triggerKeywords: ['batch delayed', 'settlement', 'external api latency'],
    steps: [
      'Pause dependent reporting jobs.',
      'Check idempotency key coverage before replay.',
      'Run settlement recovery task with the delayed time window.',
      'Notify finance operations after reconciliation completes.',
    ],
    linkedIncidentIds: [94],
  },
  {
    id: 204,
    title: 'DB connection pool exhaustion checklist',
    serviceName: 'order-api',
    category: 'Database',
    owner: 'order-oncall',
    updatedAt: '2026-06-10T13:00:00',
    triggerKeywords: ['HikariPool', 'connection timeout', 'pool exhausted'],
    steps: [
      'Inspect active connection count and slow query dashboard.',
      'Check recently deployed code for transaction scope changes.',
      'Identify endpoints with increased p95 latency.',
      'Scale read replicas or shed non-critical traffic if saturation persists.',
    ],
    linkedIncidentIds: [87],
  },
  {
    id: 205,
    title: 'JWT signing key cache mismatch',
    serviceName: 'auth-api',
    category: 'Authentication',
    owner: 'identity-team',
    updatedAt: '2026-06-20T16:30:00',
    triggerKeywords: ['JWT', 'signing key', '401', 'kid'],
    steps: [
      'Compare active signing key id with application cache state.',
      'Refresh key cache for all auth API instances.',
      'Rollback the deployment if token validation errors continue.',
      'Add a post-incident action to validate key cache warm-up in deployment checks.',
    ],
    linkedIncidentIds: [82],
  },
]

export const analyses: AiAnalysis[] = [
  {
    id: 301,
    incidentId: 101,
    createdAt: '2026-07-07T14:34:00',
    confidenceScore: 82,
    summary:
      'The payment incident is likely caused by downstream payment-provider latency surfacing as gateway 502 responses.',
    suspectedCauses: [
      'External payment provider timeout increased beyond the gateway response window.',
      'Payment API retry behavior may amplify upstream latency under checkout traffic.',
      'Gateway timeout setting is shorter than the observed provider p95 latency.',
    ],
    checkSteps: [
      'Compare gateway 502 rate with payment provider latency and retry queue depth.',
      'Inspect payment-api thread pool and outbound HTTP timeout settings.',
      'Check whether recent payment deployment changed retry or timeout policies.',
    ],
    recommendedActions: [
      'Keep checkout in degraded mode for provider-dependent payment methods.',
      'Drain retry backlog after provider latency recovers.',
      'Add a runbook note for provider timeout threshold and escalation owner.',
    ],
    relatedIncidentIds: [88, 72],
    relatedRunbookIds: [201, 202],
    rawResponse:
      '{"summary":"downstream timeout likely","confidence":82,"recommendedActions":["degraded mode","retry backlog drain"]}',
  },
  {
    id: 302,
    incidentId: 98,
    createdAt: '2026-07-05T09:34:00',
    confidenceScore: 74,
    summary:
      'Connection resets are isolated to the external SaaS provider and can be mitigated with capped retries.',
    suspectedCauses: ['External SaaS connection resets', 'Retry exhaustion during sync spikes'],
    checkSteps: ['Verify provider incident notice', 'Review retry exhaustion count'],
    recommendedActions: ['Enable capped retry mode', 'Replay failed sync window'],
    relatedIncidentIds: [77],
    relatedRunbookIds: [202],
    rawResponse: '{"summary":"external SaaS reset","confidence":74}',
  },
  {
    id: 303,
    incidentId: 94,
    createdAt: '2026-07-02T22:38:00',
    confidenceScore: 68,
    summary:
      'Settlement batch delay was caused by external settlement API latency exceeding retry windows.',
    suspectedCauses: ['External settlement API latency', 'Retry window too short'],
    checkSteps: ['Check settlement provider p95 latency', 'Validate replay idempotency'],
    recommendedActions: ['Replay delayed settlement window', 'Extend retry window after review'],
    relatedIncidentIds: [66],
    relatedRunbookIds: [203],
    rawResponse: '{"summary":"settlement latency","confidence":68}',
  },
  {
    id: 304,
    incidentId: 82,
    createdAt: '2026-06-22T11:28:00',
    confidenceScore: 91,
    summary:
      'Auth errors were caused by deployment-time signing key cache mismatch across auth API instances.',
    suspectedCauses: ['Signing key cache mismatch', 'Deployment order skipped cache warm-up'],
    checkSteps: ['Compare active kid with cache state', 'Check deployment sequence'],
    recommendedActions: ['Refresh key cache', 'Add preflight cache validation'],
    relatedIncidentIds: [58],
    relatedRunbookIds: [205],
    rawResponse: '{"summary":"key cache mismatch","confidence":91}',
  },
]

export const resolutions: ResolutionHistory[] = [
  {
    id: 401,
    incidentId: 98,
    actionSummary: 'Enabled capped retry and replayed failed profile sync jobs.',
    rootCause: 'External SaaS provider reset long-running connections during maintenance.',
    resolvedBy: 'platform-oncall',
    resolvedAt: '2026-07-05T10:02:00',
    preventionNotes: 'Add provider status polling to the sync-worker incident checklist.',
  },
  {
    id: 402,
    incidentId: 94,
    actionSummary: 'Replayed delayed settlement window after provider latency recovered.',
    rootCause: 'External settlement API p95 latency exceeded the batch retry window.',
    resolvedBy: 'data-platform',
    resolvedAt: '2026-07-03T00:15:00',
    preventionNotes: 'Update retry threshold and add replay dry-run check.',
  },
  {
    id: 403,
    incidentId: 82,
    actionSummary: 'Refreshed signing key cache and rolled forward with cache warm-up check.',
    rootCause: 'Auth deployment used stale signing key cache on two instances.',
    resolvedBy: 'identity-team',
    resolvedAt: '2026-06-22T12:44:00',
    preventionNotes: 'Add key cache validation to deployment pipeline.',
  },
]

export const feedbacks: AiFeedback[] = [
  {
    id: 501,
    incidentId: 98,
    rating: 'HELPFUL',
    note: 'The retry queue check was the fastest clue.',
    createdAt: '2026-07-05T10:08:00',
  },
  {
    id: 502,
    incidentId: 82,
    rating: 'PARTIAL',
    note: 'The suspected cause was correct, but the action needed identity-team context.',
    createdAt: '2026-06-22T13:05:00',
  },
]
