create table incidents (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    service_name varchar(120) not null,
    severity varchar(30) not null,
    status varchar(30) not null,
    source varchar(30) not null,
    owner varchar(120) not null,
    affected_users integer not null,
    description text not null,
    occurred_at timestamp not null,
    updated_at timestamp not null,
    keywords text,
    related_runbook_ids text,
    similar_incident_ids text
);

create table incident_logs (
    id bigint generated by default as identity primary key,
    incident_id bigint not null references incidents(id),
    level varchar(20) not null,
    source varchar(120) not null,
    message text not null,
    captured_at timestamp not null,
    extracted_keywords text
);

create table runbooks (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    service_name varchar(120) not null,
    category varchar(120) not null,
    owner varchar(120) not null,
    updated_at timestamp not null,
    trigger_keywords text,
    steps text,
    linked_incident_ids text
);

create table ai_analyses (
    id bigint generated by default as identity primary key,
    incident_id bigint not null references incidents(id),
    created_at timestamp not null,
    confidence_score integer not null,
    summary text not null,
    suspected_causes text,
    check_steps text,
    recommended_actions text,
    related_incident_ids text,
    related_runbook_ids text,
    raw_response text not null
);

create table resolution_history (
    id bigint generated by default as identity primary key,
    incident_id bigint not null references incidents(id),
    action_summary text not null,
    root_cause text not null,
    resolved_by varchar(120) not null,
    resolved_at timestamp not null,
    prevention_notes text
);

create table ai_feedback (
    id bigint generated by default as identity primary key,
    incident_id bigint not null references incidents(id),
    rating varchar(30) not null,
    note text not null,
    created_at timestamp not null
);
